---
- name: Install Basic System Utilities
  hosts: all
  become: yes
  tasks:
    - name: Install Essential Utilities
      apt:
        name:
          - git
          - nano
          - wget
          - curl
          - build-essential
          - busybox
          - iptables
          - ufw
          - gparted
          - parted
          - ntfs-3g
        state: present
      tags: utilities

    - name: Install File Sharing Utilities
      apt:
        name:
          - samba
          - smbclient
          - nfs-common
        state: present
      tags: file_sharing

    - name: Install Security Utilities
      apt:
        name:
          - openssl
          - openssh-client
          - ca-certificates
        state: present
      tags: security

    - name: Install Development Tools
      apt:
        name:
          - software-properties-common
          - vim
          - tree
          - htop
          - zip
          - unzip
          - nano
          - gedit
          - git
          - net-tools
          - dnsutils
          - traceroute
          - rsync
          - lsof
          - tcpdump
          - iproute2
          - tar
          - gzip
          - bzip2
          - make
          - gcc
          - g++
          - gdb
        state: present
      tags: development

    - name: Install Python and Java
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - perl
          - default-jre
          - default-jdk
        state: present
      tags: python_java

    - name: Install System Monitoring Utilities
      apt:
        name:
          - preload
          - zram-config
          - gnome-disk-utility
        state: present
      tags: system_monitoring

    - name: Install Intel IoT Tools and Linux Tools
      apt:
        name:
          - linux-intel-iotg-tools-common
          - linux-tools-common
        state: present
      tags: iot_linux_tools

    - name: Install Network Utilities
      apt:
        name:
          - net-tools
          - ifconfig
          - unattended-upgrades
          - apt-listchanges
          - network-manager
        state: present
      tags: network
    - name: Install Disk and Partition Management tools
      apt:
        name:
          - gparted
          - gnome-disk-utility
          - lsblk
          - fdisk
          - gdisk
          - parted
          - sfdisk
          - cgdisk
          - smartmontools
          - hdparm
          - gddrescue
          - testdisk
          - ddrescue
          - lvm2
          - thin-provisioning-tools
          - mdadm
          - multipath-tools
          - clonezilla
          - fsarchiver
          - partclone
          - partimage
        state: present

    - name: Install Data Recovery and Backup tools
      apt:
        name:
          - extundelete
          - foremost
          - rclone
          - rsync
          - grsync
          - syncthing
          - duplicity
          - timeshift
          - backintime-qt
          - photorec
        state: present

    - name: Install Filesystem and Storage Utilities
      apt:
        name:
          - ncdu
          - duf
          - pv
          - btrfs-progs
          - xfsprogs
          - e2fsprogs
          - dosfstools
          - mtools
          - ntfs-3g
          - exfatprogs
          - squashfs-tools
          - f2fs-tools
          - nbd-client
          - open-iscsi
          - targetcli-fb
          - bcache-tools
          - reiserfsprogs
          - jfsutils
          - hfsplus
          - nilfs-tools
          - xfsdump
          - fatresize
          - fatsort
          - exfat-fuse
          - smbclient
          - cifs-utils
          - samba
          - nfs-common
          - nfs-kernel-server
          - sshfs
          - bindfs
          - archivemount
          - util-linux
          - coreutils
          - dmraid
          - dmsetup
          - quota
          - quotatool
          - acl
          - attr
          - inotify-tools
          - incron
          - logrotate
          - mc
          - p7zip-full
          - zip
          - unzip
          - ark
          - file-roller
          - fdupes
          - rdfind
          - bleachbit
          - secure-delete
          - wipe
          - cryptsetup
          - ecryptfs-utils
          - encfs
          - dar
          - dar-static
          - sleuthkit
          - autopsy
          - tmux
          - screen
          - iotop
          - blktrace
          - stress
          - stress-ng
          - ethtool
          - hwinfo
          - lshw
          - inxi
          - fio
        state: present

    - name: Install System and Network Utilities
      apt:
        name:
          - openssh-server
          - openssh-client
          - sshfs
          - build-essential
          - vim
          - nano
          - git
          - curl
          - wget
          - htop
          - tree
          - gnupg
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - openssl
          - jq
          - dnsutils
          - net-tools
          - iputils-ping
          - tcpdump
          - iptables
          - traceroute
          - uuid-runtime
          - gzip
          - bzip2
          - xz-utils
          - file
          - gnupg2
          - gawk
          - gettext
          - locales
          - strace
          - lsof
          - sysstat
          - time
          - whois
          - zstd
          - parallel
          - multitail
          - vnstat
          - make
          - gcc
          - g++
          - gdb
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          - python3-setuptools
          - python3-wheel
          - open-vm-tools
          - lm-sensors
          - fancontrol
          - ufw
          - unattended-upgrades
          - apt-listchanges
          - aptitude
          - udisks2
          - sg3-utils
          - scsitools
          - iftop
          - nmon
          - atop
          - ioping
          - bonnie++
          - arp-scan
          - arptables
          - bridge-utils
          - iperf
          - iperf3
          - ipset
          - iptstate
          - mtr
          - nmap
          - btop
          - tshark
          - aide
          - apparmor
          - apparmor-utils
          - auditd
          - clamav
          - fail2ban
          - nftables
          - rkhunter
          - unhide
          - perl
          - default-jre
          - default-jdk
          - dirmngr
          - preload
        state: present

    - name: Install Development Libraries
      apt:
        name:
          - libarchive-dev
          - libcurl4-gnutls-dev
          - liblzma-dev
          - qtbase5-dev
          - qtbase5-dev-tools
          - qtdeclarative5-dev
          - libqt5svg5-dev
          - qttools5-dev
          - libgnutls28-dev
          - qml-module-qtquick2
          - qml-module-qtquick-controls2
          - qml-module-qtquick-layouts
          - qml-module-qtquick-templates2
          - qml-module-qtquick-window2
          - qml-module-qtgraphicaleffects
        state: present
